eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/**
          filters:
            - StripPrefix=1
        - id: flight-ms
          uri: lb://flight-ms
          predicates:
            - Path=/flight-ms/**
          filters:
            - StripPrefix=1
        - id: baggage-ms
          uri: lb://baggage-ms
          predicates:
            - Path=/baggage-ms/**
          filters:
            - StripPrefix=1