eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-ms
          uri: lb://auth-ms
          predicates:
            - Path=/auth-ms/**
          filters:
            - StripPrefix=1
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/**
          filters:
            - StripPrefix=1